<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Veil.DriverHelper</AssemblyName>
    <RootNamespace>Veil.DriverHelper</RootNamespace>
    <StartupObject>Veil.DriverHelper.Program</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\installer\payload.manifest.json" Link="payload.manifest.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Veil.Engine\Veil.Engine.csproj" />
  </ItemGroup>
</Project>
