<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>false</UseWindowsForms>
    <AssemblyName>Veil.Recovery</AssemblyName>
    <RootNamespace>Veil.Recovery</RootNamespace>
    <StartupObject>Veil.Recovery.Program</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Veil.Engine\Veil.Engine.csproj" />
  </ItemGroup>
</Project>
