[workspace]
resolver = "2"
members = [
    "veil-engine",
    "veil-recovery",
    "veil-driver-helper",
    "veil-app",
]

[workspace.package]
version = "0.1.4"
edition = "2021"
license = "MIT"
publish = false

[workspace.metadata.veil]
suffix = "preview.1"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
